export const data = {
  list: [
    {
      country: 'Australia',
      currency: 'dollar',
      amount: 1,
      code: 'AUD',
      rate: 16.446,
    },
    {
      country: 'Brazil',
      currency: 'real',
      amount: 1,
      code: 'BRL',
      rate: 4.683,
    },
    {
      country: 'Bulgaria',
      currency: 'lev',
      amount: 1,
      code: 'BGN',
      rate: 12.566,
    },
    {
      country: 'Canada',
      currency: 'dollar',
      amount: 1,
      code: 'CAD',
      rate: 18.518,
    },
    {
      country: 'China',
      currency: 'renminbi',
      amount: 1,
      code: 'CNY',
      rate: 3.51,
    },
    {
      country: 'Croatia',
      currency: 'kuna',
      amount: 1,
      code: 'HRK',
      rate: 3.256,
    },
    {
      country: 'Denmark',
      currency: 'krone',
      amount: 1,
      code: 'DKK',
      rate: 3.294,
    },
    {
      country: 'EMU',
      currency: 'euro',
      amount: 1,
      code: 'EUR',
      rate: 24.495,
    },
    {
      country: 'Hongkong',
      currency: 'dollar',
      amount: 1,
      code: 'HKD',
      rate: 3.135,
    },
    {
      country: 'Hungary',
      currency: 'forint',
      amount: 100,
      code: 'HUF',
      rate: 6.063,
    },
    {
      country: 'Iceland',
      currency: 'krona',
      amount: 100,
      code: 'ISK',
      rate: 17.711,
    },
    {
      country: 'IMF',
      currency: 'SDR',
      amount: 1,
      code: 'XDR',
      rate: 31.862,
    },
    {
      country: 'India',
      currency: 'rupee',
      amount: 100,
      code: 'INR',
      rate: 30.862,
    },
    {
      country: 'Indonesia',
      currency: 'rupiah',
      amount: 1000,
      code: 'IDR',
      rate: 1.646,
    },
    {
      country: 'Israel',
      currency: 'new shekel',
      amount: 1,
      code: 'ILS',
      rate: 7.148,
    },
    {
      country: 'Japan',
      currency: 'yen',
      amount: 100,
      code: 'JPY',
      rate: 17.183,
    },
    {
      country: 'Malaysia',
      currency: 'ringgit',
      amount: 1,
      code: 'MYR',
      rate: 5.426,
    },
    {
      country: 'Mexico',
      currency: 'peso',
      amount: 1,
      code: 'MXN',
      rate: 1.224,
    },
    {
      country: 'New Zealand',
      currency: 'dollar',
      amount: 1,
      code: 'NZD',
      rate: 14.653,
    },
    {
      country: 'Norway',
      currency: 'krone',
      amount: 1,
      code: 'NOK',
      rate: 2.401,
    },
    {
      country: 'Philippines',
      currency: 'peso',
      amount: 100,
      code: 'PHP',
      rate: 42.886,
    },
    {
      country: 'Poland',
      currency: 'zloty',
      amount: 1,
      code: 'PLN',
      rate: 5.196,
    },
    {
      country: 'Romania',
      currency: 'leu',
      amount: 1,
      code: 'RON',
      rate: 4.976,
    },
    {
      country: 'Singapore',
      currency: 'dollar',
      amount: 1,
      code: 'SGD',
      rate: 17.464,
    },
    {
      country: 'South Africa',
      currency: 'rand',
      amount: 1,
      code: 'ZAR',
      rate: 1.392,
    },
    {
      country: 'South Korea',
      currency: 'won',
      amount: 100,
      code: 'KRW',
      rate: 1.77,
    },
    {
      country: 'Sweden',
      currency: 'krona',
      amount: 1,
      code: 'SEK',
      rate: 2.277,
    },
    {
      country: 'Switzerland',
      currency: 'franc',
      amount: 1,
      code: 'CHF',
      rate: 25.567,
    },
    {
      country: 'Thailand',
      currency: 'baht',
      amount: 100,
      code: 'THB',
      rate: 66.551,
    },
    {
      country: 'Turkey',
      currency: 'lira',
      amount: 1,
      code: 'TRY',
      rate: 1.346,
    },
    {
      country: 'United Kingdom',
      currency: 'pound',
      amount: 1,
      code: 'GBP',
      rate: 28.03,
    },
    {
      country: 'USA',
      currency: 'dollar',
      amount: 1,
      code: 'USD',
      rate: 24.606,
    },
  ],
  date: '16 Sep 2022 ',
};
